# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de1289932c30f87444eeb589a2fba75986d33560028f58ff95836442528ffb3a9805784ba9cfe7bd0516004282d44926e0a1a5a04e89078e9bb6191560a14ffa

test:
  secret_key_base: d3d656dd8f1c26e9b120fe68b8ceafbd2157aa39c7e0eef41905f5d3452064c3d06d74b72af9e5c9858aca002d5afe63ad198d4181d202cd0cf3bea5657760fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
